server:
  port: 8080

spring:
  application:
    name: nexusops-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: auth
          uri: lb://nexusops-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: app
          uri: lb://nexusops-app
          predicates:
            - Path=/app/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
