server:
  port: 8084

spring:
  application:
    name: nexusops-alert
  datasource:
    url: jdbc:postgresql://localhost:5432/nexusops
    username: postgres
    password: password
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  level:
    com.nexusops: DEBUG
