server:
  port: 8082

spring:
  application:
    name: nexusops-app
  datasource:
    url: jdbc:postgresql://localhost:5432/nexusops
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        boot:
          # 使得 Hibernate 不再尝试在启动期间访问 JDBC 元数据，以避免 Hibernate 在刷新阶段之前联系远程数据库
          allow-jdbc-driver-metadata: false

logging:
  level:
    com.nexusops: DEBUG
