server:
  port: 8082

spring:
  application:
    name: nexusops-app
  datasource:
    url: jdbc:postgresql://localhost:5432/nexusops
    username: postgres
    password: password
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  level:
    com.nexusops: DEBUG
