server:
  port: 8081

spring:
  application:
    name: nexusops-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/nexusops
    username: postgres
    password: 123456
  redis:
    host: localhost
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: true

logging:
  level:
    com.nexusops: DEBUG
